### PR TITLE
Audio visualizer

### PR DESCRIPTION
**Pull request by Megidd**
## Description

To address this issue: https://github.com/mediacms-io/mediacms/issues/109#issuecomment-1022880199

### CODE REVIEW

**Comment by Megidd** [comment]
## Try

It's tried to use the `videojs-wavesurfer` plugin.

https://collab-project.github.io/videojs-wavesurfer/#/usage

## Approach

I have tried this approach to build and test the changes:

```bash
### CMS has developed a custom NPM package based on videojs.
### Maybe we can add `videojs-wavesurfer` plugin to this custom NPM package.

cd /home/mediacms.io/mediacms/frontend/packages/player

### https://stackoverflow.com/a/61103357/3405291
rm package-lock.json

### For some reason, a symbolic link is corrupt.
### Has to be fixed:
cd /home/mediacms.io/mediacms/frontend/packages/vjs-plugin/node_modules
ln -svf ../../vjs-plugin-font-icons mediacms-vjs-plugin-font-icons

cd /home/mediacms.io/mediacms/frontend/packages/player
npm14 install videojs-wavesurfer

### Import videojs-wavesurfer inside the custom package.
### Add wavesurfer as a plugin.
### The exact commit to be looked at.

cd /home/mediacms.io/mediacms/frontend/packages/player
npm14 run build
```

## Implication so far

For some reason, `videojs-wavesurfer` plugin is not enabled. It's a work-in-progress.

**Comment by Megidd** [comment]
## Try another appraoch

Commit efcebfc4164d7c5eddf6f1ce6ac7919b0a93efda tries another approach.

```bash
cd /home/mediacms.io/mediacms/frontend
npm14 install --save videojs-wavesurfer

### Commit uses videojs-wavesurfer

cd /home/mediacms.io/mediacms
docker-compose -f docker-compose-dev.yaml exec -T frontend npm run dist
cp -r frontend/dist/static/* static/
```

## Implication

For some reason, the `videojs-wavesurfer` is not working.

**Comment by Megidd** [comment]
## Try integrating `video.js` only first

1. As [suggested](https://github.com/collab-project/videojs-wavesurfer/issues/154#issuecomment-1027208895), it's tried to use `video.js` only by commit 038b846117ac2ee8a9b68de27f03e2f08048579b.
1. Then, the `videojs-wavesurfer` plugin is tried by commit adc9dad12fb643ebca99febda76c1105c98b504a.

## Error

However, I'm receiving this error:

> Uncaught TypeError: Cannot read properties of undefined (reading 'params')

At this line:

```javascript
// videojs.wavesurfer.js:148 

          var WavesurferMiddleware = {
            setSource: function setSource(srcObj, next) {
              if (this.player.usingPlugin('wavesurfer')) {
                var backend = this.player.wavesurfer().surfer.params.backend; // ** error line.
                var src = srcObj.src;
                var peaks = srcObj.peaks;

                switch (backend) {
                  case 'WebAudio':
```

## Debug

I'm trying to figure out the error cause...

**Comment by Megidd** [comment]
## Implication so far

Initializing `videojs` instance without the plugin is fine and audio is played. But as soon as the plugin is added, the audio is *not* played :

```javascript
              plugins: {
                // enable videojs-wavesurfer plugin
                wavesurfer: {
                  // configure videojs-wavesurfer
                  backend: 'MediaElement',
                  displayMilliseconds: true,
                  debug: true,
                  waveColor: '#163b5b',
                  progressColor: 'black',
                  cursorColor: 'black',
                  hideScrollbar: true
                }
              }
```

With the plugin, this error is thrown:

> Uncaught TypeError: Cannot read properties of undefined (reading 'params')
> 
> videojs.wavesurfer.js:148

**Comment by Megidd** [comment]
Replacing `"video.js": "^7.12.3"` with the latest `"video.js": "^7.17.0"` didn't help.

**Comment by mgogoulos** [comment]
awesome work so far! @styiannis what do you think?

**Comment by Megidd** [comment]
Commit 0840fb3f112456b34a6c908a6193b232c5c28793 tries to use the `videojs-wavesurfer` plugin by `MediaPlayer.js`. But for some reason the audio is *not* visualized:

image

# Guess

`mediacms-vjs-plugin` is a custom package used by `MediaPlayer.js`. My guess is that I need to understand how to use `videojs-wavesurfer` plugin alongside another `mediacms-vjs-plugin` custom package :question: 

```json
  "dependencies": {
    "mediacms-vjs-plugin": "file:../vjs-plugin",
```

**Comment by Megidd** [comment]
Commit 40a45a7b70ddfc3d0c9cabc5858426921b86dc3e tries to debug. The audio is *not* visualized and an error is thrown:

image

**Comment by Megidd** [comment]
# Next

Using `videojs-wavesurfer` plugin by `MediaPlayer.js` didn't work. Next is to try to use it by this custom package:

```json
  "dependencies": {
    "mediacms-vjs-plugin": "file:../vjs-plugin"
  },
```

Which is actually implemented by `frontend/packages/vjs-plugin/src/MediaCmsVjsPlugin.js`.

**Comment by Megidd** [comment]
Commit f768206fa4106cb47e5186905edc92baaf217051 implements another way of registering and initializing `videojs-wavesurfer` plugin.

But an error is thrown:

> Uncaught TypeError: this.player.wavesurfer is not a function

At this line:

image

Audio is played, but it's not visualized:

image

# Implication

Implication is the videojs-wavesurfer plugin didn't get registered properly.

**Comment by Megidd** [comment]
To resolve the previous error, commit b0b14e30a713e3e37ce012d5bd36aff8fe90989e tries to register the `videojs-wavesurfer` plugin manually. But a new error is thrown:

> Uncaught Error: Illegal plugin for "wavesurfer", must be a function, was object.

image

**Pull request closed without merging**
