### PR TITLE
Add workflow for docker build and push

### PR DESCRIPTION
**Pull request by Adito5393**
## Summary

This PR adds automation to build and deploy the Docker image to Docker Hub through two triggers:
- Every push to the main branch
- Every tag with the format `v*.*.*` (see https://semver.org/ for more information)

If you prefer to deploy only on tags and not on every branch push, you can remove lines 5 and 6:
```yml
branches:
  - main
```

Additionally, two secret variables are required in the GitHub settings:
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN

The token can be generated from https://hub.docker.com/settings/security.

Please merge this PR to enjoy the automation.

## Testing

I tested this PR by forking the repo and deploying it at https://hub.docker.com/r/adito5393/mediacms/tags. 
The development was done on the [add-dockerhub-release-with-all-tags branch](https://github.com/Adito5393/mediacms/tree/add-dockerhub-release-with-all-tags). 
The GitHub Actions output can be viewed at https://github.com/Adito5393/mediacms/actions/workflows/docker-build-push.yml.

### CODE REVIEW

**Comment by Adito5393** [comment]
Hey @mgogoulos 

I have organized the CI jobs to ensure that the software does not get released if it fails the unit tests or linting. For more details, see:
- https://docs.github.com/en/actions/using-workflows/reusing-workflows
- https://docs.github.com/en/actions/using-workflows/about-workflows#creating-dependent-jobs

[Here](https://github.com/techno-tim/k3s-ansible/actions/runs/4547185972) you can see the CI output of a project with similar workflow dependency layout.

**Comment by mgogoulos** [comment]
Awesome work @Adito5393 , I will review it during this week. Thanks a lot

**Comment by Adito5393** [comment]
Hey @mgogoulos,
Congrats on the new v2.0.0 release! 

**What is holding this PR to be merged? Is there anything I can help with?**
Such that we can rely on the official docker images for rolling back versions! (especially now with a major release, would have been awesome to have it already merged)

At the moment, the only DockerHub tag available is the `latest` 😔

**Comment by mgogoulos** [comment]
Hi, it has just been a matter of not having enough capacity to test it. But your instructions are very good, so I am now merging it after having created the two secret variables

**Comment by mgogoulos** [comment]
Merged, thanks for this! It might require some calibration, as it happens in similar cases where some new workflow is introduced, let's find out!

**Comment by mgogoulos** [comment]
@Adito5393 please let me know if you want to help in other issues too. There are devops/infrastructure/dev experience related tickets, as upgrade of all libraries and software, improve the Docker Compose files, provide a clear path for Developmnent etc so it would be great to help there too, or on other issues that interest you more!

**Comment by Adito5393** [comment]
Hey, thanks! I will be available for support for whatever calibration is required.
I'll have a look at the issue tracker, but meanwhile, PR #749 is ready for review! You can remove the minor version and pin only the major version of the DB. (because now 15.3 is the [latest released](https://hub.docker.com/_/postgres/))
The addition of the TZ variable is based on the [tzdata package being available](https://github.com/docker-library/postgres/blob/master/15/alpine3.18/Dockerfile).

**Comment by Adito5393** [comment]
By the way, I just noticed that you have [Automated Builds](https://docs.docker.com/docker-hub/builds/) setup via DockerHub UI(?!):
image

I recommend disabling it because you only want to build the docker image if your commits/changes pass the tests. This is handled by the new GitHub Action workflow.

**Comment by mgogoulos** [comment]
I've disabled it, it was part of DockerHub

**Comment by Adito5393** [comment]
It fails because the secrets are probably disabled in PR. We can modify the job `release` to be skipped if it is a PR.
The following part from [ci.yml](.github/workflows/ci.yml) should be:
```yml
  release:
    uses: ./.github/workflows/docker-build-push.yml
    needs: [test]
    if: github.event_name != 'pull_request'
```
I will test it on my fork this evening and let you know if it works.

You might also want to skip CI for all files inside the `docs` directory, via [paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths):
```yml
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
```

**Comment by mgogoulos** [comment]
This works, and i also changed on ci.yml to use `main` instead of `master`. 

However, it is still unable to read the repository secrets, and this is very weird :(

**Comment by Adito5393** [comment]
Hm, it was a syntax error... I guess your last commit fixed it a1962d4b328c8ea2d47308b2cda273f217a098bd
You can add the username as a env variable and use [[ci skip]](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs)

**Comment by Adito5393** [comment]
The debug logs clearly show that the secrets are not set:
```log
##[debug]Evaluating: secrets.DOCKERHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'DOCKERHUB_TOKEN'
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
```
Could you remove it and try a new token? (maybe it expired?!)

**Comment by mgogoulos** [comment]
I'm pausing for now but will try out tomorrow again. I did remove it and then added it a couple of times, and I even added it as an organization secret, but on all cases it shows as null on the debug logs. Something strange happening here!

**Comment by mgogoulos** [comment]
https://github.com/mediacms-io/mediacms/commit/1fd04ca947b393070c0162abe79490bd963e1b8f
that fixed it, the secrets needed to be inhereted, since this is using a workflow (and not a straight yml file)

**Pull request merged**
