### PR TITLE
feat: Added Elestio as one-click deploy option

### LINKED ISSUE #1054: Adding Elestio as deployment option
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing MediaCMS application as shown [here](https://elest.io/open-source/mediacms). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

### PR DESCRIPTION
**Pull request by kaiwalyakoparkar**
## Description

This PR introduces new one-click deployment option

Fixes #1054

### CODE REVIEW

**Comment by mgogoulos** [comment]
Hi @kaiwalyakoparkar 

I'm fine merging this but I think you have to find a better place to add it, I think placing a section `Self-Hosting MediaCMS` and have elestion below this would be confusing, as people realize Self hosting is the chance to run it anywhere, not on a single service provider. 

I think a section in `Support and paid services` would be better. Eg a sub section 'commercial hosting' or similar.  What do you think?

**Comment by kaiwalyakoparkar** [comment]
Hey @mgogoulos, that sounds nice. I will soon make changes to this pr according to your suggestions and we can work on additional updates if needed :)

**Comment by kaiwalyakoparkar** [comment]
@mgogoulos let me know what you think about this ✨

**Comment by mgogoulos** [comment]
looks good, thanks!

**Pull request merged**
