### PR TITLE
Add pre-commit 

### LINKED ISSUE #131: [Tool/Feature] Add pre-commit to ensure the code quality
Since this repo contains python as well as Javascript code, I was thinking maybe we can have a sort of rule check in the form of pre-commit config, which can help us to maintain the code quality according to standard jslint and PEP conventions. 
@mgogoulos what do you think? 
If it's something that you feel we can add, please let me know. I can work on this!
Thank you!

### PR DESCRIPTION
**Pull request by shubhank-saxena**
This fixes #131 
@mgogoulos please let me know if there are any further changes required.
Thank you!

### CODE REVIEW

**Comment by swiftugandan** [comment]
You can also extend this further and add a github action. See: https://levelup.gitconnected.com/raise-the-bar-of-code-quality-in-python-projects-7c49743f004f

**Comment by shubhank-saxena** [comment]
> You can also extend this further and add a github action. See: https://levelup.gitconnected.com/raise-the-bar-of-code-quality-in-python-projects-7c49743f004f

This was the next thing on my mind. Will do this. Thank you!

**Comment by shubhank-saxena** [comment]
@swiftugandan done! Please add a secret in the repo settings named CI_TOKEN. This should be a Personal Access Token allowing the Read/Write commit.

**Comment by swiftugandan** [comment]
* I was expecting one file ie. `.github/workflows/lint_test.yml`
* What is this file used for? `.github/lint_test.yml`
* According to https://github.com/pre-commit/action, we should use `${{ secrets.GITHUB_TOKEN }}` and its automatically provisioned, we dont have to do anything

**Comment by shubhank-saxena** [comment]
@swiftugandan fixed!

**Comment by mgogoulos** [comment]
Ok most probably lots of changes need to be done after merging this, but seems like a good start. Merging

**Pull request merged**
